app = "suafesta"

primary_region = "gru"

[build]
  image = "ruby:3.1"

[env]
  RAILS_ENV = "production"

[deploy]
  release_command = "bundle exec rails db:migrate"

[processes]
  app = "bundle exec puma -C config/puma.rb"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 0
