app = "festavip"
primary_region = "gru"

[env]
RAILS_ENV = "production"

[build]
  secrets = ["RAILS_MASTER_KEY"]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
