app = "festavip" # ou o nome do seu app no Fly.io

primary_region = "gru" # ou altere para o mais próximo de você

[build]
# Sem buildpacks — usa Dockerfile automaticamente

[env]
RAILS_ENV = "production"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
size = "shared-cpu-1x"
memory = "512mb"
