version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    command: sleep infinity
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3000:3000"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
