default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: suafesta_development
  user: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: suafesta_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
